package com.github.gfx.android.orma_kotlin_example

import io.realm.RealmObject
import io.realm.annotations.Index
import java.util.*

open class RealmTodo : RealmObject() {

    // The primary key is generated by Realm

    @Index
    var title: String? = null

    var content: String? = null

    var done: Boolean = false

    @Index
    var createdTime: Date = Date()
}
